### PR TITLE
Potential fixes for the Travis CI build on 1.9.3

### PR DESCRIPTION
**Pull request by mdeering**
Why:
- "rake test" portion of the build is broken
- https://travis-ci.org/katgironpe/textile_editor_helper/builds/75128504

This change addresses the need by:
- Get pull request I have submitted passing.  Pull request is failing
  due to these issue and not any real issues with the code.
  https://github.com/katgironpe/textile_editor_helper/pull/7

### CODE REVIEW

**Comment by mdeering** [comment]
Looks like these fixes for travis work @katgironpe let me know if there is anything I can do help with a release of this or any future maintenance. Would gladly help out if you are busy.

Thanks,
Mike D.

**Comment by katgironpe** [comment]
@mdeering Looks good. I will merge. Thank you!

**Comment by mdeering** [comment]
You hit the wrong button? "Closed with unmerged commits"

I will keep the branch around for a bit longer.

**Comment by kathgironpe** [comment]
@mdeering It's on master branch now. Thank you! The unit tests are run independent of the integration tests so there's a minor difference with the `test_helper.rb` changes.

**Pull request closed without merging**
